name: view_engine_example
description: "A new Serinus application"
version: 1.0.0
publish_to: 'none'


environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  mustachex: ^1.0.0
  serinus:
    path: ../../packages/serinus
  
