openapi: "3.1.0"
paths:
  /:
    get:
      tags:
        - "AppController"
      parameters: []
      responses:
        200:
          description: "Success response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
  /post/<data>:
    post:
      tags:
        - "AppController"
      parameters:
        - name: "data"
          in: "path"
          required: true
      responses:
        201:
          description: "Success response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
  /a/:
    get:
      tags:
        - "App2Controller"
      parameters: []
      responses:
        200:
          description: "Success response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
  /a/post:
    post:
      tags:
        - "App2Controller"
      parameters: []
      responses:
        201:
          description: "Success response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
info:
  title: "My API"
  description: "This is my API"
  version: "1.0.0"
