FROM dart:latest AS build

WORKDIR /app

COPY . ./
COPY pubspec.* ./
RUN dart pub get
COPY . .

RUN dart pub get --offline
RUN mkdir -p dist
RUN dart compile exe {{$entrypoint}} -o dist/{{$output}}

FROM scratch
EXPOSE {{$port}}
COPY --from=build /runtime/ /
COPY --from=build /app/dist/{{$output}} /app/bin/

CMD ["/app/bin/{{$output}}"]