name: serinus_frontier
description: A module for Serinus applications that exposes the frontier package allowing you to use all the auth strategies.
version: 1.0.0
repository: https://github.com/francescovallone/serinus
homepage: https://serinus.app
documentation: https://serinus.app/plugins/frontier.html
topics:
  - server
  - httpserver
  - backend
  - web
  - authentication

environment:
  sdk: '>=3.5.0 <4.0.0'

resolution: workspace

# Add regular dependencies here.
dependencies:
  serinus: ^2.0.0-rc.4
  frontier: ^1.0.0

dev_dependencies:
  lints: "^6.0.0"
  test: ^1.26.3
