name: serinus_frontier
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  serinus: ^0.6.0
  frontier: ^0.0.1

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
  test: ^1.24.0
