name: Serinus Frontier Tests

on:
  pull_request:
    paths:
      - ".github/workflows/serinus_frontier.yml"
      - "packages/serinus_frontier/lib/**"
      - "packages/serinus_frontier/test/**"
      - "packages/serinus_frontier/pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/serinus_frontier.yml"
      - "packages/serinus_frontier/lib/**"
      - "packages/serinus_frontier/test/**"
      - "packages/serinus_frontier/pubspec.yaml"

jobs:
  build:    
    defaults:
      run:
        working-directory: ./packages/serinus_frontier
    runs-on: "ubuntu-latest"
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: 📦 Install Dependencies
        run: dart pub get

      - name: 🕵️ Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: 🧪 Run Tests
        run: |
          dart pub global activate coverage
          dart test --coverage=coverage && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=${{inputs.report_on}}
      
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
